### ISSUE TITLE
API Url changed?

### ISSUE THREAD

**Issue by Suplanus** [RobThree/NPushOver#1]
Could it be that the url changed? 
https://pushover.net/api

Reference is to https://api.pushover.net/1/ not to https://api.pushover.net/

Get a 400 error.

**Comment by RobThree** [comment]
Works perfectly fine for me?

Did you notice that the [`DEFAULTBASEURI`](https://github.com/RobThree/NPushOver/blob/master/NPushOver/PushOver.cs#L35) is used as, well... , base-uri? And it refers to `https://api.pushover.net/`. The `1/` part is [always added](https://github.com/RobThree/NPushOver/blob/90c7ee47c020ee4731fa5064c28d0acd19bed483/NPushOver/PushOver.cs#L241) by the [`GetV1APIUriFromBase`](https://github.com/RobThree/NPushOver/blob/master/NPushOver/PushOver.cs#L634) method. The `https://pushover.net/api` url is only used in documentation / TODO references.

If you still encounter this problem then some code to reproduce would be nice.

**Comment by Suplanus** [comment]
1. Problem: after reboot VS2015 the exception isnt fired
2. Delay of pushing i think
   Sorry, you can close the issue.
   Thanks for the great lib!
