### ISSUE TITLE
Issue with a vb.net project

### ISSUE THREAD

**Issue by Arnaud-31** [RobThree/NPushOver#2]
Hello Rob,

I have tried your solution in a vb.net project (VS 2015) :
I generate the dll for NPushOver reference it on my project and do a simple test like your hello word in a windows form application.
I have a issue cause it never go out of the Task.WaitAll(sendtask1)
The notification is sended but never go to the next line of my code

I've done the same in your test application in C# an all is ok.

Any idea ?

Thanks

Arnaud

**Comment by RobThree** [comment]
There shouldn't be any difference. You'll need to post some code to reproduce the issue (preferably a stripped-down testcase of some sorts). Then we can take a look and maybe help you figure out the problem.

**Comment by Arnaud-31** [comment]
Hello
I want to put a zip file but I can't :-(

So create a vb.net windows form project

add a reference to your dll

Open the source of the form1 form

At the top, before the Public class :

``` vb.net
Imports System.Threading.Tasks
Imports NPushover
Imports NPushover.ResponseObjects
```

Create a button on the form and put the code :

```
Dim po = New NPushover.Pushover("[APPLICATION-KEY-HERE]")
Dim msg1 = NPushover.RequestObjects.Message.Create("Hello world!")
Dim sendtask1 = po.SendMessageAsync(msg1, "[RECIPIENT-ID-HERE]")
Task.WaitAll(sendtask1)
MessageBox.Show("OK")
```

You will never have the OK, and if you press the pause on debug, it is stopped on the waillall

thanks

Arnaud

**Comment by RobThree** [comment]
I'll test tonight to see if I can reproduce.

> add a reference to your dll

Why don't you use the [NuGet package](https://www.nuget.org/packages/NPushover/)?

**Comment by Arnaud-31** [comment]
Cause I'm newbie ;-)

**Comment by RobThree** [comment]
Try this:

``` vb.net
Private Async Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
    Dim po = New NPushover.Pushover("[APPLICATION-KEY-HERE]")
    Dim msg1 = NPushover.RequestObjects.Message.Create("Hello world!")
    Dim sendtask1 = po.SendMessageAsync(msg1, "[RECIPIENT-ID-HERE]")
    Await sendtask1
    MessageBox.Show("OK")
End Sub
```

Note the **Async** keyword in the `Private Async Sub Button1_Click(...)` method declaration and the `Await` keyword instead of the `Task.WaitAll(...)`.

**Comment by Arnaud-31** [comment]
Yes, it's ok now
thanks a lot, I can now continue to make tests with your lib
Have a good day !
