### ISSUE TITLE
Exception when canceling a Notification

### ISSUE THREAD

**Issue by Arnaud-31** [RobThree/NPushOver#3]
Hello Rob, ... I'm back ;-)
When I send a emergency notification, It works, I got the receipt but I can't cancel it after, I got a 404 Not found exception :

``` c#
var po = new Pushover("[APPLICATION-KEY-HERE]");

var msg2 = Message.Create(Priority.Emergency, "The roof!", "The roof is on fire!", false, Sounds.Siren);

msg2.RetryOptions = new RetryOptions { RetryEvery = TimeSpan.FromSeconds(30), RetryPeriod = TimeSpan.FromHours(3) };
msg2.SupplementaryUrl = new SupplementaryURL { Uri = new Uri("http://robiii.me"), Title = "Awesome dude!" };
var sendtask2 = po.SendMessageAsync(msg2, "[RECIPIENT-ID-HERE]", "[DEVICE-ID-HERE]");

Task.WaitAll(sendtask2);

var receipt = sendtask2.Result.Receipt;

System.Threading.Thread.Sleep(5000);

var sendtask3 = po.CancelReceiptAsync(receipt);

try
{
    Task.WaitAll(sendtask3);
}
catch (Exception ex)
{
    Console.WriteLine (ex.Message );
}
```

I also got an exception with the GetReceiptAsync.

Is It a problem from your lib or from PushOver ?

Thanks,

Arnaud

**Comment by RobThree** [comment]
The problem is you using Task.WaitAll instead of async/await keywords. The solution here is exactly the same; add async keyword to method and await the sendtasks. This has nothing to do with Pushover or the lib.

**Comment by Arnaud-31** [comment]
Ok, that's what I've done.

See my VB.NET code : 

``` vb.net
Private Async Sub btnAnnul_Emergency_Click(sender As Object, e As EventArgs) Handles btnAnnul_Emergency.Click
    Dim po As New NPushover.Pushover("[APPLICATION-KEY-HERE]")
    Dim sendtask1 As Task(Of NPushover.ResponseObjects.PushoverUserResponse)
    sendtask1 = po.CancelReceiptAsync("[RECEIPT-ID HERE]")
    Try
        Await sendtask1
    Catch ex As Exception
        MsgBox(ex.Message)
    End Try
End Sub
```

**Comment by RobThree** [comment]
Something like this should work:

``` vb.net
Imports NPushover
Imports NPushover.RequestObjects

Public Class Form1
    Private receiptid As String
    Private po As New Pushover("aUbXjdXQHwUuZu1XEACU2mhLCkwGVe")

    Private Async Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim alertMsg = Message.Create(Priority.Emergency, "The roof!", "The roof is on fire!", False, Sounds.Siren)

        alertMsg.RetryOptions = New RetryOptions
        With alertMsg.RetryOptions
            .RetryEvery = TimeSpan.FromSeconds(30)
            .RetryPeriod = TimeSpan.FromHours(3)
        End With
        Dim alertResult = Await po.SendMessageAsync(alertMsg, "uUe9oLZ923YMvtdadRqzbm1dnzvcDF")
        receiptid = alertResult.Receipt
    End Sub

    Private Async Sub Button2_Click(sender As Object, e As EventArgs) Handles Button2.Click
        Await po.CancelReceiptAsync(receiptid)
    End Sub
End Class
```

(Form with 2 buttons, 1 to send, 1 to cancel).

However, the cancel seems to return a 404; not sure what is going on there. Will look into that.

**Comment by RobThree** [comment]
There seems to be a bug in the `CancelReceiptAsync()` method. Will fix asap.

**Comment by Arnaud-31** [comment]
Ok, have a look to the GetReceiptAsync method too it has also an exception

Thanks a lot and have a good day

Arnaud

**Comment by RobThree** [comment]
Please, when stating something has "an exception", state **which** exception / the exception message.

**Comment by Arnaud-31** [comment]
Ok Rob but my messages are in French, so it's a bit difficult to translate.

So when I call a GetReceiptAsync("[My Receipt ID])" method I got the exception in French :
"L'index (de base zéro) doit être supérieur ou égal à zéro et inférieur à la taille de la liste des arguments."

I will translate it : "The Index (zero based) must be greater or equal to the size of the list of arguments"

**Comment by RobThree** [comment]
Update your NuGet package and (should be 1.2 now) and let me know if that [fixes](https://github.com/RobThree/NPushOver/commit/28fcc474cfb31d7d06749de28f8cc92c9a2ec1a1#diff-2928ce6947359180d2d980105975b7c0L669) your problem(s).

**Comment by Arnaud-31** [comment]
Yes, it does for the two methods.

Thanks a lot Rob
